packages:
  - 'apps/*'
  - 'packages/*'
  - 'servers/bff'
  - 'servers/microservices'
  - 'servers/libs'
  - 'servers/jobs'
  - 'scripts'

catalog:
  eslint: 9.39.2
  prettier: 3.7.4
  typescript: 5.9.3
  '@eslint/js': 9.39.2
  eslint-config-prettier: 10.0.1
  eslint-plugin-prettier: 5.2.2
  globals: 16.0.0
  typescript-eslint: 8.20.0
